services:
  - type: web
    name: innovationhub-web
    runtime: node
    plan: free
    buildCommand: npm install; npm run build
    startCommand: npm start
    autoDeploy: false
    envVars:
      - key: PORT
        value: 3000
